### ISSUE TITLE
課題5. GitHub APIを利用して、指定したリポジトリの情報を取得し、リスト形式で表示するアプリを作成する 

### ISSUE THREAD

**Issue by MinatoIshiwata** [retail-oukaku/flutter_study#11]
## 条件
- StatefulWidgetの機能を利用すること
- riverpodを利用しないこと
- https://docs.github.com/ja/rest?apiVersion=2022-11-28
- Freezedを利用しない
- json_serializableを利用してhttps://github.com/immutable、copyWithなどを利用すること
## 期限
5日

**Comment by retail-oukaku** [comment]
done
